# Set to the name of the single label you want to generate data for
target_label: "right_lunge"
multi_label: False # Set to True if you want to generate data for all movement_labels
use_joint_angles: True # Set to True if you want to use joint angles to filter frames
input_dir: "./labeller_input"
output_dir: "./labeller_output"
save_overlay_video: True # Saves video(s) with overlayed pose
log_dir: "./logs/labeller"
log_level: "INFO"

blaze_settings:
  static_image_mode: False
  model_complexity: 1
  smooth_landmarks: True
  enable_segmentation: False
  smooth_segmentation: True
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5


#     - name: "KNEE" # maps to angle between hip-knee-ankle
#     - name: "ELBOW" # maps to angle between shoulder-elbow-wrist
#     - name: "SHOULDER" # maps to using angle between elbow-shoulder-hip
#     - name: "HIP" # maps to using angle between shoulder-hip-knee
movement_labels:
  jumping_jacks:
    joints: # joint angle thresholds to define the movements KNEE, ELBOW, SHOULDER, HIP
      - name: "SHOULDER"
        side: "BOTH"
        min_angle: 30
        max_angle: 200
      - name: "HIP"
        side: "BOTH"
        min_angle: 0
        max_angle: 180

  right_lunge:
    joints:
      - name: "KNEE"
        side: "RIGHT"
        min_angle: 0
        max_angle: 160
      - name: "KNEE"
        side: "LEFT"
        min_angle: 150
        max_angle: 210

  left_lunge:
    joints:
      - name: "KNEE"
        side: "LEFT"
        min_angle: 0
        max_angle: 160
      - name: "KNEE"
        side: "RIGHT"
        min_angle: 150
        max_angle: 210

  squat:
    joints:
      - name: "KNEE"
        side: "BOTH"
        min_angle: 0
        max_angle: 120
      - name: "HIP"
        side: "BOTH"
        min_angle: 30
        max_angle: 70

